### ISSUE TITLE
how can i close connect from web or api

### ISSUE THREAD

**Issue by breathlq** [openstf/stf#185] opened 2015-11-24 10:26 UTC
I just want to close the connect between stf and phone from web page or api. what should i do?

**Comment by gunta** [comment] 2015-11-24 10:29
Duplicate of #83.

**Closed by gunta** 2015-11-24 10:29 UTC

**Comment by breathlq** [comment] 2015-11-24 10:33
i dont want to stop using, what i want is to close the connect and free 5555 port. how can i do that :(

**Comment by vbanthia** [comment] 2015-11-24 11:32
Could you give more details about your use case. With current information, we are not getting anything.
