### ISSUE TITLE
Could you support Android Q

### ISSUE THREAD

**Issue by zhangpeng23796** [openstf/stf#1048] opened 2019-05-09 10:12 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Android Q has published, Now there are some mobile models have android Q ROM, Could you support Android Q

**Describe alternatives you've considered**

**Additional context**

**Comment by koral--** [comment] 2019-06-21 15:08
Duplicate of https://github.com/openstf/stf/issues/1028

**Closed by koral--** 2019-06-21 15:08 UTC
