### ISSUE TITLE
I want to ask if minitouch can achieve multi touch? Is there a solution?

### ISSUE THREAD

**Issue by jhflovehqy** [openstf/stf#1218] opened 2020-04-15 07:36 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by koral--** [comment] 2020-04-18 17:27
Duplicate of https://github.com/openstf/minitouch/issues/64

**Closed by koral--** 2020-04-18 17:27 UTC
