### ISSUE TITLE
cannot launch agent

### ISSUE THREAD

**Issue by channingbreeze** [openstf/stf#108] opened 2015-10-13 03:45 UTC
Hi, i use nexus 5 and install android 6.0 on it, but when i start stf, i find the error below
can you give me some suggestions to fix the problem? thank you

INF/device:plugins:service 19293 [0642e51a005db76f] Launching agent
FTL/device 19293 [0642e51a005db76f] Setup had an error TimeoutError: operation timed out
    at Timer.listOnTimeout (timers.js:119:15)
From previous event:
    at /home/zhuxun/COMPANY/stf/stf/lib/units/device/plugins/service.js:80:14
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at openAgent (/home/zhuxun/COMPANY/stf/stf/lib/units/device/plugins/service.js:77:10)
    at /home/zhuxun/COMPANY/stf/stf/lib/units/device/plugins/service.js:699:12
    at SerialSyrup.ParallelSyrup.invoke (/home/zhuxun/COMPANY/stf/stf/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /home/zhuxun/COMPANY/stf/stf/node_modules/stf-syrup/lib/serial.js:43:33
    at process._tickCallback (node.js:355:11)
FTL/util:lifecycle 19293 [0642e51a005db76f] Shutting down due to fatal error

**Comment by sorccu** [comment] 2015-10-13 03:46
Build from master, 1.0.10 isn't compatible yet.

**Comment by sorccu** [comment] 2015-10-13 16:19
Duplicate of #105.

**Closed by sorccu** 2015-10-13 16:19 UTC
Labels: duplicate
