### ISSUE TITLE
Change mock auth to ldap 

### ISSUE THREAD

**Issue by romitincedoinc** [openstf/stf#215] opened 2015-12-31 10:20 UTC
Hi

I m trying to figure out the auth module which is mock by default. now i want to change it to ldap and connect it to my ldap server. So could you  please help in finding the file in which i need to perform changes.

**Comment by vbanthia** [comment] 2015-12-31 11:28
To use ldap, you will need to start you stf-auth unit using ldap settings. You can find ldap related options using `stf auth-ldap --help` command. After reconfiguration restart you `stf-auth` unit.

In case you are using `stf local` then check ldap related options using `stf local --help`

**Comment by vbanthia** [comment] 2015-12-31 11:31
or check https://github.com/openstf/stf/issues/47

**Comment by romitincedoinc** [comment] 2015-12-31 11:55
Thanks For your quick reply. Let me try with oAuth & with Ldap.

**Comment by vbanthia** [comment] 2016-01-04 08:16
Duplicate of https://github.com/openstf/stf/issues/47

**Closed by vbanthia** 2016-01-04 08:16 UTC
