### ISSUE TITLE
Latest version brings Invalid argument (tcp.cpp:121) error related to zeromq (zmq)

### ISSUE THREAD

**Issue by ma3tk** [openstf/stf#139] opened 2015-10-21 09:35 UTC
Hi. I met a bug. I had used latest version of openstf/stf in dockerfiles.
When I updated `openstf/stf:latest`, our journalctl shows below.
```
systemd[1]: Started STF dev triproxy.
docker[21135]: INF/triproxy 1 [dev] PUB socket bound on tcp://*:7250
docker[21135]: INF/triproxy 1 [dev] DEALER socket bound on tcp://*:7260
docker[21135]: INF/triproxy 1 [dev] PULL socket bound on tcp://*:7270
docker[21135]: Invalid argument (tcp.cpp:121)
systemd[1]: stf-triproxy-dev.service: main process exited, code=exited, status=139/n/a
```

And I checked `docker ps`, then stf-triproxy-dev rescheduled many times.
I found an issue and Pull Request related to the error.
https://github.com/openstf/stf/issues/109 https://github.com/openstf/stf/commit/b248e96dc2582f0176b3a75468fa18ab0036c3e1
Also, I assume that these codes are something bad for my environment.
https://github.com/JustinTulloss/zeromq.node/blob/master/lib/index.js#L324

My environment is Ubuntu 15.04, and zeromq libraries are
```
ii  libzmq1:amd64                       2.2.0+dfsg-6                        amd64        lightweight messaging kernel (shared library)
rc  libzmq3:amd64                       4.0.5+dfsg-2+deb8u1build0.15.04.1   amd64        lightweight messaging kernel (shared library)
ii  libzmq5:amd64                       4.1.2-1                             amd64        lightweight messaging kernel (shared library)
ii  libzmq5-dev:amd64                   4.1.2-1                             amd64        lightweight messaging kernel (development files)
```

Now I have changed from `openstf/stf:latest` to `openstf/stf:1.0.10` in all dockerfiles related to openstf, instead.

Thanks.

**Comment by sorccu** [comment] 2015-10-21 11:32
You're right. This was caused by #104, although only on some platforms (by mac and boot2docker were both perfectly fine). I've pushed a fix and the latest docker image should solve the issue. You can check #104 for more details.

**Comment by sorccu** [comment] 2015-10-21 11:33
By the way, if you use docker, your host system doesn't need to have zeromq installed. It's included in the docker image.

**Closed by sorccu** 2015-10-21 11:32 UTC

**Comment by ma3tk** [comment] 2015-10-22 01:49
>  It's included in the docker image.

Thanks. I use docker with service files in `DEPLOYMENT.md`.

I checked #104 yesterday before I post this. Also, I have removed all docker images yesterday, and pulled newest docker images. Of course I also killed all systemd processes (services) about this system.
 #104 made 13 days ago from now, but something odd to me because I made my STF environment yesterday. That's why I posted this Issue.

Thankfully, now I can see both you guys are checking this issue, and zeromq.
I will report after fixing bug with `openstf/stf:latest`.
