### ISSUE TITLE
after screenshot，the image is broken

### ISSUE THREAD

**Issue by niuniudd** [openstf/stf#364] opened 2016-07-11 05:58 UTC
## What's the problem (or question)?

click the button screenshot，and also found the image file in directory:/tmp
but when I click the image icon in the stf web page,don` display the image
stf output is:
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (external/MY_minicap/src/minicap_21.cpp:269) Publishing virtual display"
INF/device:plugins:screen:stream 4974 [ab6e5747] Connecting to minicap service 
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 6268932 bytes for JPG encoder" 
INF/device:plugins:screen:stream 4974 [ab6e5747] Reading minicap banner INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (jni/minicap/minicap.cpp:444) New client connection" INF/device:plugins:screen:capture 4974 [ab6e5747] Capturing screenshot INF/storage:temp 4795 [_] Uploaded "ab6e5747.jpg" to "/tmp/upload_0a4dad3844e1728b0d7a55f4419d0f12" 
INF/device:support:storage 4974 [ab6e5747] Uploaded to "/s/image/f8c68514-5b68-4008-8b00-8c73b1989f6f/ab6e5747.jpg" 
INF/device:plugins:screen:capture 4974 [ab6e5747] Capturing screenshot 
INF/storage:temp 4795 [_] Uploaded "ab6e5747.jpg" to "/tmp/upload_dbbd561d6f6ca81caab609902ef580f6" 
INF/device:support:storage 4974 [ab6e5747] Uploaded to "/s/image/025a24b7-2c12-47fe-8f7e-7aa2447879d9/ab6e5747.jpg" 
INF/device:plugins:screen:stream 4974 [ab6e5747] Requesting frame producer to stop 
INF/device:plugins:screen:stream 4974 [ab6e5747] Disconnecting from minicap service 
INF/device:plugins:screen:stream 4974 [ab6e5747] Stopping minicap service 
INF/device:plugins:screen:stream 4974 [ab6e5747] Sending SIGTERM to minicap 
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (jni/minicap/minicap.cpp:196) Received SIGTERM, stopping" 
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (jni/minicap/minicap.cpp:512) Closing client connection" 
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (external/MY_minicap/src/minicap_21.cpp:284) Destroying virtual display" 
INF/device:plugins:screen:stream 4974 [ab6e5747] Keeping 555x854 as current frame producer projection 
INF/device:plugins:screen:stream 4974 [ab6e5747] Requesting frame producer to start 
INF/device:plugins:screen:stream 4974 [ab6e5747] Launching screen service 
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "PID: 11411" 
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: Using projection 1080x1920@480x854/0" 
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (external/MY_minicap/src/minicap_21.cpp:240) Creating SurfaceComposerClient" 
INF/device:plugins:screen:stream 4974 [ab6e5747] Connecting to minicap service 
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (external/MY_minicap/src/minicap_21.cpp:243) Performing SurfaceComposerClient init check" 
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (external/MY_minicap/src/minicap_21.cpp:250) Creating virtual display" 
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (external/MY_minicap/src/minicap_21.cpp:256) Creating buffer queue" 
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (external/MY_minicap/src/minicap_21.cpp:261) Creating CPU consumer" 
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (external/MY_minicap/src/minicap_21.cpp:265) Creating frame waiter" 
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (external/MY_minicap/src/minicap_21.cpp:269) Publishing virtual display" 
INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 6268932 bytes for JPG encoder" 
INF/device:plugins:screen:stream 4974 [ab6e5747] Reading minicap banner INF/device:plugins:screen:stream 4974 [ab6e5747] minicap says: "INFO: (jni/minicap/minicap.cpp:444) New client connection"
this is the screenshot for the webpage
![image](https://cloud.githubusercontent.com/assets/14904226/16720937/e4f98086-476d-11e6-8590-2493077d6921.png)
## What should have happened?

when I click the image icon in the stf web page,I should see the image
## How can we reproduce the issue?

1.
2.
3.
4.
## Please tell us details about your environment.

- Are you using `stf local` or a [full deployment](doc/DEPLOYMENT.md): 
- Version used (git hash or `stf -V`): stf -V 1.1.1
- Environment name and version (e.g. Chrome 39, node.js 5.4): 
  gm -version :GraphicsMagic 1.3.24 2016-05-30
  node -v :v6.3.0
- Operating System and version: Ubuntu 14.0.4 64bit
- If there was a problem with a specific device, run `adb devices -l` and paste the relevant row here:

**Comment by 0x88l** [comment] 2016-07-12 00:22
I also encountered the same problem.Can I see your export of "stf doctor"?I think there is the version of 
module was wrong.

**Comment by niuniudd** [comment] 2016-07-12 01:05
@0x88l I run the command：stf doctor，but output is nothing

root@dd-OptiPlex-3020:/home/dd/# stf doctor
root@dd-OptiPlex-3020:/home/dd/#

**Comment by 0x88l** [comment] 2016-07-12 01:21
You haven't   link  stf ?

**Comment by niuniudd** [comment] 2016-07-12 01:28
@0x88l link?I already start rethinkdb and stf ,and how link?

**Comment by 0x88l** [comment] 2016-07-12 01:55
How did you start stf?The command "stf doctor" is one of parameter.You can see stf --help.I don't know why the "stf doctor" output nothing.

**Comment by niuniudd** [comment] 2016-07-12 01:56
@0x88l I used this command：stf local to start stf

**Comment by bentonglove** [comment] 2017-02-02 15:25
I have exactly the same problem as niuniudd had. Can someone help out there? Thanks!

**Comment by sorccu** [comment] 2017-02-02 16:03
So far, 19/20 times, this error has been caused by the gm binary either not
being installed or not being in PATH.

**Comment by bentonglove** [comment] 2017-02-04 13:24
Thanks for comments @sorccu.
Here is my gm status, is that possible to fix the problem from these information?


ben@uBentu:~$ gm -version
----------------------------------------------------------------------------------------------
GraphicsMagick 1.3.25 2016-09-05 Q8 http://www.GraphicsMagick.org/
Copyright (C) 2002-2016 GraphicsMagick Group.
Additional copyrights and licenses apply to this software.
See http://www.GraphicsMagick.org/www/Copyright.html for details.

Feature Support:
  Native Thread Safe       yes
  Large Files (> 32 bit)   yes
  Large Memory (> 32 bit)  yes
  BZIP                     no
  DPS                      no
  FlashPix                 no
  FreeType                 no
  Ghostscript (Library)    no
  JBIG                     no
  JPEG-2000                no
  JPEG                     no
  Little CMS               no
  Loadable Modules         no
  OpenMP                   yes (201307)
  PNG                      no
  TIFF                     no
  TRIO                     no
  UMEM                     no
  WebP                     no
  WMF                      no
  X11                      yes
  XML                      no
  ZLIB                     no

Host type: x86_64-unknown-linux-gnu

Configured using the command:
  ./configure 

Final Build Parameters:
  CC       = gcc
  CFLAGS   = -fopenmp -g -O2 -Wall -pthread
  CPPFLAGS = 
  CXX      = g++
  CXXFLAGS = -pthread
  LDFLAGS  = 
  LIBS     = -lSM -lICE -lX11 -lm -lgomp -lpthread

ben@uBentu:~$ whereis gm
gm: /usr/local/bin/gm

ben@uBentu:~$ echo $PATH
/home/ben/Android/SDK/tools:/home/ben/Android/SDK/platform-tools:/home/ben/bin:/home/ben/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/protobuf/bin/:/home/ben/.linuxbrew/bin/
----------------------------------------------------------------------------------------------


I also found my stf doctor has some problem, will that "TypeErro" cause the problem too?

ben@uBentu:~$ stf doctor
----------------------------------------------------------------------------------------------
INF/util:doctor 15899 [*] OS Arch: x64
INF/util:doctor 15899 [*] OS Platform: linux
INF/util:doctor 15899 [*] OS Platform: 4.4.0-59-generic
INF/util:doctor 15899 [*] Using Node 6.9.5
INF/util:doctor 15899 [*] Using RethinkDB client 2.3.3
INF/util:doctor 15899 [*] Using ZeroMQ 4.1.4
INF/util:doctor 15899 [*] ProtoBuf 3.1.0
ERR/util:doctor 15899 [*] Current ProtoBuf version is not supported, it has to be 2
INF/util:doctor 15899 [*] GraphicsMagick 1.3.25
INF/util:doctor 15899 [*] Local RethinkDB server 2.3.5 0xenial
/usr/lib/node_modules/stf/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 2.3.5~0xenial
    at new SemVer (/usr/lib/node_modules/stf/node_modules/semver/semver.js:293:11)
    at Range.test (/usr/lib/node_modules/stf/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/usr/lib/node_modules/stf/node_modules/semver/semver.js:1085:16)
    at unsupportedVersion (/usr/lib/node_modules/stf/lib/util/doctor.js:13:15)
    at /usr/lib/node_modules/stf/lib/util/doctor.js:95:7
    at /usr/lib/node_modules/stf/lib/util/doctor.js:50:22
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)





And below is the log once I clicked on Screenshot button. I am able to find the screenshot in the host folder /tmp/upload_6e7289d078ac4d977794997f2fd4ef94
But the link in URL "http://localhost:7100/s/image/3b9ab278-2ef1-4c61-bdc4-b8feeef3d5b4/152085230D0026.jpg" are broken.

----------------------------------------------------------------------------------------------
INF/device:plugins:screen:stream 15842 [152085230D0026] minicap says: "INFO: (jni/minicap/minicap.cpp:448) New client connection"
INF/device:plugins:screen:capture 15842 [152085230D0026] Capturing screenshot
INF/storage:temp 15801 [*] Uploaded "152085230D0026.jpg" to "/tmp/upload_6e7289d078ac4d977794997f2fd4ef94"
INF/device:support:storage 15842 [152085230D0026] Uploaded to "/s/image/3b9ab278-2ef1-4c61-bdc4-b8feeef3d5b4/152085230D0026.jpg"

**Comment by xiaobeiying** [comment] 2017-02-22 02:56
@bentonglove  Screenshot isnot work here. I also have "ProtoBuf" problem.
```
administrator@ubuntu:~$ stf doctor
INF/util:doctor 16163 [*] OS Arch: x64
INF/util:doctor 16163 [*] OS Platform: linux
INF/util:doctor 16163 [*] OS Platform: 3.13.0-24-generic
INF/util:doctor 16163 [*] Using Node 7.4.0
INF/util:doctor 16163 [*] Using RethinkDB client 2.3.3
INF/util:doctor 16163 [*] Using ZeroMQ 4.1.4
INF/util:doctor 16163 [*] GraphicsMagick 1.3.21
INF/util:doctor 16163 [*] ProtoBuf 3.0.0
ERR/util:doctor 16163 [*] Current ProtoBuf version is not supported, it has to be ~2
INF/util:doctor 16163 [*] Local ADB 1.0.31
INF/util:doctor 16163 [*] Local RethinkDB server 2.3.5~0trusty
/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 2.3.5~0trusty
    at new SemVer (/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:293:11)
    at Range.test (/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:1085:16)
    at unsupportedVersion (/usr/local/lib/node_modules/stf/lib/util/doctor.js:13:15)
    at /usr/local/lib/node_modules/stf/lib/util/doctor.js:95:7
    at /usr/local/lib/node_modules/stf/lib/util/doctor.js:50:22
    at ChildProcess.exithandler (child_process.js:202:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```
Do you have resolved this problem？  
@sorccu Need your help...

**Comment by sorccu** [comment] 2017-02-22 03:13
There have been at least 20 issues about this thing. So far, in 99% of the
cases, it has been an issue with the the gm binary not being found.

I would highly recommend pasting the stf log output from when you take the
screenshot, all the way till you see the broken image. Otherwise there's
nothing more I can say.

**Comment by xiaobeiying** [comment] 2017-02-22 03:22
@sorccu  STF log as follow:
`INF/device:plugins:screen:capture 15914 [LGE9805310cdab] Capturing screenshot
  adb:command Send '001Dhost:transport:LGE9805310cdab' +9s
  adb:command Send '0089shell:LD_LIBRARY_PATH=/data/local/tmp exec /data/local/tmp/minicap -P 1080x1920@1080x1920/0 -s >/data/local/tmp/minicap_1487733564309.jpg' +1ms
  adb:command Send '001Dhost:transport:LGE9805310cdab' +293ms
  adb:command Send '0005sync:' +1ms
  adb:sync STAT /data/local/tmp/minicap_1487733564309.jpg +2ms
  adb:command Send '001Dhost:transport:LGE9805310cdab' +2ms
  adb:command Send '0005sync:' +1ms
  adb:sync RECV /data/local/tmp/minicap_1487733564309.jpg +1ms
INF/storage:temp 2949 [*] Uploaded "LGE9805310cdab.jpg" to "/tmp/upload_1b7a49095cf5b486e435b0a82891c900"
INF/device:support:storage 15914 [LGE9805310cdab] Uploaded to "/s/image/9b990945-5bdd-4368-a9db-11c19d8fcb71/LGE9805310cdab.jpg"
  adb:command Send '001Dhost:transport:LGE9805310cdab' +130ms
  adb:command Send '003Bshell:'rm' '-f' '/data/local/tmp/minicap_1487733564309.jpg'' +4ms
INF/device:plugins:screen:stream 15914 [LGE9805310cdab] Requesting frame producer to stop
INF/device:plugins:screen:stream 15914 [LGE9805310cdab] Disconnecting from minicap service
INF/device:plugins:screen:stream 15914 [LGE9805310cdab] Stopping minicap service
INF/device:plugins:screen:stream 15914 [LGE9805310cdab] Sending SIGTERM to minicap
  adb:command Send '001Dhost:transport:LGE9805310cdab' +29s
  adb:command Send '0016shell:'kill' -15 31608' +0ms
INF/device:plugins:screen:stream 15914 [LGE9805310cdab] minicap says: "INFO: (jni/minicap/minicap.cpp:197) Received SIGTERM, stopping"
INF/device:plugins:screen:stream 15914 [LGE9805310cdab] minicap says: "INFO: (jni/minicap/minicap.cpp:516) Closing client connection"
INF/device:plugins:screen:stream 15914 [LGE9805310cdab] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:297) Destroying virtual display"
`

**Comment by xiaobeiying** [comment] 2017-02-22 03:28
I also have stf environment on my mac, everything is all right.

**Closed** 2017-06-03 08:35 UTC
