### ISSUE TITLE
a bug about logcat

### ISSUE THREAD

**Issue by channingbreeze** [openstf/stf#92] opened 2015-09-28 11:56 UTC
i find a bug here about logcat
if you start control one device and open logcat , do not close it
then you start control another deivce and open logcat
what will happen
the logcat is mixed , how can i fix it ?

**Comment by deathlord87** [comment] 2018-05-02 23:58
this group.leave() has already a stop logcat hook, I doubt that the logcat works at after initial/start/stop.

Second time starting/stopping the logcat doesn't start logcat at all.

**Comment by lukzeg** [comment] 2019-09-11 09:37
Hi,
I noticed the same issue. 

Steps to reproduce:
a) Assign first device and enable collecting adb logs
b) return to device list
c) select second device

Actual Results:
The logs for first device are displayed in the logcat textView.

Expected Results:
The logs should be separated between selected/assigned for the user devices

Some ideas:
During free time (to help my old friends) I started work on separating logs and restoring filters for selected by the user devices. I created array, which separated logs collected for different devices, also stores information about filters assigned to them which give possibility to have better control from user perspective site.
Also as the end user I noticed that it will be good to have possibility to save logs to file.
I added option to save logs in *json* and classic *txt* format.
The implementation, maybe not beautiful one, but working you can find at:
https://github.com/lukzeg/stf/tree/feature/separate-device-logs
I will try to create a PR with changes. Maybe some will be interested to use it.

**Comment by koral--** [comment] 2020-02-08 21:23
Closing this issue since mentioned PR was merged.
However, feel free to comment if something is still wrong.

**Closed by koral--** 2020-02-08 21:23 UTC
Labels: need triage
