### ISSUE TITLE
Multiple OpenSTF- server's at multiple connections and how to configure the providers

### ISSUE THREAD

**Issue by habeebshk** [openstf/stf#946] opened 2018-09-07 20:41 UTC
**What is the issue or idea you have?**
My setup is based on the mercari openstf and has created accordingly, I have two servers A and B in different locations in google cloud and have the devices connected to it using reverse SSH. everything is fine now till now but I am not able to determine how to configure the provider so that I can access both the devices from both the locations. I read from some other issues that i need to modify the commands in the stf-provider but I don't figure out how?
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**
Here are my configurations 
Nginx: [for one my server]
  ``` daemon off;
worker_processes 4;

events {
  worker_connections 1024;
}

http {
  upstream stf_app {
    server 192.168.3.16:3100 max_fails=0;
  }

  upstream stf_auth {
    server 192.168.3.16:3200 max_fails=0;
  }

  upstream stf_storage_apk {
    server 192.168.3.16:3300 max_fails=0;
  }

  upstream stf_storage_image {
    server 192.168.3.16:3400 max_fails=0;
  }

  upstream stf_storage {
    server 192.168.3.16:3500 max_fails=0;
  }

  upstream stf_websocket {
    server 192.168.3.16:3600 max_fails=0;
  }

  types {
    application/javascript  js;
    image/gif               gif;
    image/jpeg              jpg;
    text/css                css;
    text/html               html;
  }

  map $http_upgrade $connection_upgrade {
    default  upgrade;
    ''       close;
  }

  server {
    listen 80;
    server_name stf.test;
    keepalive_timeout 70;
    root /dev/null;

    resolver 127.0.0.1 valid=300s;
    resolver_timeout 10s;

    # Handle stf-provider@floor4.service
    location ~ "^/d/floor4/([^/]+)/(?<port>[0-9]{5})/$" {
      proxy_pass http://192.168.3.16:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }
             # Handle stf-provider@floor5.service
    location ~ "^/d/floor5/([^/]+)/(?<port>[0-9]{5})/$" {
      proxy_pass http://192.152.3.11:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location /auth/ {
      proxy_pass http://stf_auth/auth/;
    }

    location /s/image/ {
      proxy_pass http://stf_storage_image;
    }

    location /s/apk/ {
      proxy_pass http://stf_storage_apk;
    }

    location /s/ {
      client_max_body_size 1024m;
      client_body_buffer_size 128k;
      proxy_pass http://stf_storage;
    }

    location /socket.io/ {
      proxy_pass http://stf_websocket;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $http_x_real_ip;
    }

    location / {
      proxy_pass http://stf_app;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $http_x_real_ip;
    }
  }
}
```
and here is the stf-provider i use: 
  ```sudo docker run -d --name provider1 --net host openstf/stf stf provider --name "provider-test" --connect-sub tcp://192.168.3.16:7250  --connect-push tcp://192.168.3.16:7270  --storage-url http://192.168.3.16  --public-ip 192.168.3.16  --min-port=15000  --max-port=25000  --heartbeat-interval 20000 --screen-ws-url-pattern "ws://stf.test/d/floor4/<%= serial %>/<%= publicPort %>/"```
[i also tried adding the other server ip in the above command but then the stf doesnot connect. and i get an error so i think that might not be the way]

**What is the expected behavior?**
   Any suggestion is greatly helpful. 
**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
All the other servers
**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment] 2018-12-30 06:46
I'm going to assume that this is a duplicate of the other issue you posted (with `stf local`).

**Closed by sorccu** 2018-12-30 06:46 UTC
