### ISSUE TITLE
Scroll with mouse wheel

### ISSUE THREAD

**Issue by hram** [openstf/stf#713] opened 2017-09-14 08:43 UTC
Can you add scrolling ability with mouse wheel how it is implemented in android emulator?

**Comment by sorccu** [comment] 2017-09-14 08:46
This has been asked in the past, search for past answers.

**Comment by Hongarc** [comment] 2020-01-20 07:54
#15 

Should close this issue(move to that issue).

**Comment by koral--** [comment] 2020-02-16 14:31
Closing as a duplicate of #15

**Closed by koral--** 2020-02-16 14:31 UTC
Labels: duplicate
