### ISSUE TITLE
How can use input keyevent faster!!!

### ISSUE THREAD

**Issue by ZENGYANYAN** [openstf/stf#400] opened 2016-08-13 09:13 UTC
WHAT A GREAT JOB！
But I find a small problem . 
when i use the adb command ,"input keyevent XXX"，it too slow .
so i want have a function call "minikey" that can input keyevent faster !
poor english , sorry ......
thanks for your coding!

**Comment by vbanthia** [comment] 2016-08-13 12:23
Duplicate of  https://github.com/openstf/minitouch/issues/5

**Closed by vbanthia** 2016-08-13 12:23 UTC
