### ISSUE TITLE
my kindle(FireOS) display broken in STF

### ISSUE THREAD

**Issue by adhirvipin** [openstf/stf#632] opened 2017-06-22 09:21 UTC
I am able to connect Kindle(FireOS) in STF but when i select the device the device display is broken in STF. 
With Android devices its working fine.
Is there anything i am missing ? Please help me with the solution?

**Comment by sorccu** [comment] 2017-06-22 09:22
Duplicate of #508.

**Closed by sorccu** 2017-06-22 09:22 UTC
