### ISSUE TITLE
Rethinkdb has problem when I connect to STF and chose a device under proxy

### ISSUE THREAD

**Issue by Tierney0115** [openstf/stf#171] opened 2015-11-11 01:39 UTC
The STF is running locally by --public-ip xxx
When my other PC connect to it if I am using proxy, the control panel is grey all the time and the log shows "Device database does not have a match for device xxx"
And this situation also happened when I connect STF from other area network's PC. (Of course they are in the same LAN because I can connect to STF, but the Control panel failed)
I think it could be the rethinkdb connection problem under proxy because the STF service works fine. 
Can I get rethinkdb work when I using proxy?
Thanks.

**Comment by vbanthia** [comment] 2015-11-11 02:06
Well, I don't think the problem is with rethinkdb. Because client never access database directly.

Regarding 
> "Device database does not have a match for device xxx"
This error means that the device which are using is not present in [STF Database](https://github.com/openstf/stf-device-db)

The grey screen problem is because client is not able to make websocket connection. `stf local` uses port range between 7400 ~ 7700 for these connections. Can you check if these ports are open? 

Better way to debug this problem is by using chrome developer tool and check what kind of error are you getting in WebSocket connections.

**Comment by Tierney0115** [comment] 2015-11-11 02:15
@vbanthia 
Thanks for your reply. Do you mean the ports on PC which running the stf local? I think both my server PC and client PC have those ports open because it works fine when I close my proxy setting. Does it relate to the proxy server's ports?

I will check the WebSocket connections. Thanks.

**Comment by vbanthia** [comment] 2015-11-11 02:52
> Do you mean the ports on PC which running the stf local?

Yeah I meant that.

Btw, What kind of proxy are you using? Can you give me more details.

In general, client will make two connection with server. One at 7100 port which is okay in your case since you can see web app. The other connection is for screen. STF will choose a port between 7400 ~ 7700 and then your client will establish a websocket connection to see device screen. Make sure that you can access these port while using proxy from your client.

**Comment by vbanthia** [comment] 2015-11-11 03:16
You can also change port range by providing `--provider-min-port` & `--provider-max-port` options while running `stf local`

**Comment by vbanthia** [comment] 2015-11-24 11:24
Closing this issue assuming problem is fixed, since the reporter has not reported any progress.

Feel free to reopen this issue if you have similar issue.

**Closed by vbanthia** 2015-11-24 11:24 UTC
