### ISSUE TITLE
stf-auth LDAP

### ISSUE THREAD

**Issue by benjamin-m-kane** [openstf/stf#99] opened 2015-10-05 15:25 UTC
Hi,
I am currently experiencing problems trying to get LDAP user authentication working. Are you able to provide me with an example of an stf-auth@.service so i can use this to help get this implemented correctly.

Thanks in advance,

Ben

**Comment by sorccu** [comment] 2015-10-13 16:30
You'd have to take the auth-mock service unit and modify it with LDAP options. You can check `stf auth-ldap --help` or #47 for guidance. I'm closing this one as a duplicate of #47 for now.

**Closed by sorccu** 2015-10-13 16:30 UTC
Labels: duplicate
