### ISSUE TITLE
Have you tried to transfer the speaker audio data to the host via the adb or something else?

### ISSUE THREAD

**Issue by likezjuisee** [openstf/stf#550] opened 2017-03-01 06:31 UTC
I have an idea, that maybe the user can listen the audio inside the phone maybe awesome.
So, did you have tried this?

**Comment by sorccu** [comment] 2017-03-01 06:33
Ideas on how to do that are welcome.

**Comment by likezjuisee** [comment] 2017-03-03 04:57
http://stackoverflow.com/questions/15125139/android-get-device-overall-audio-output-in-pcm

I have tried this method, but the audio's quality is too low, can't heard clearly. Perhaps the native lib corresponds to the java be better.

**Comment by alisamir82** [comment] 2017-04-24 13:17
you might feed the device audio via host-PC's mic.

I believe there is a node to capture mic audio and stream it to the client browser.

**Comment by sorccu** [comment] 2017-12-06 08:07
I'm closing this as a duplicate of #22.

**Closed by sorccu** 2017-12-06 08:07 UTC
Labels: duplicate
