### ISSUE TITLE
feature request for Android OS 10 devies

### ISSUE THREAD

**Issue by JulianLiu1511** [openstf/stf#1121] opened 2019-10-25 09:53 UTC
Hi， 
thanks you reading my request. please try to support the Android OS 10 devices connection.
in China, some Huawei devices(for example: huawei P30) could upgrade the OS version from 9 to 10.

**Comment by koral--** [comment] 2019-10-26 12:41
Duplicate of #1028

**Closed by koral--** 2019-10-26 12:41 UTC
Labels: duplicate
