### ISSUE TITLE
No image after connection

### ISSUE THREAD

**Issue by dududiao** [openstf/stf#531] opened 2017-02-06 08:53 UTC
I only use a mobile phone and data cable connection is successful, the details of the phone can be seen, but not the projection image. What shall I do? Please help me, thank you.
![qq 20170206164633](https://cloud.githubusercontent.com/assets/16865038/22640234/b10a7a9a-ec8c-11e6-9634-e628bf3ae4a9.jpg)

**Comment by sorccu** [comment] 2017-02-06 09:14
Could be a firewall issue. Could be a misconfiguration. Could be anything. Open developer tools and see what the WebSocket request is returning. If it shows that it's unable to connect, then I'd suggest temporarily disabling your firewall to see if that helps.

**Comment by dududiao** [comment] 2017-02-06 09:42
Firewall and anti-virus software are closed, the display is connected successfully, no error data. Connection is often interrupted, see other replies, is the reason for the MAC system?
![1](https://cloud.githubusercontent.com/assets/16865038/22641851/65f95326-ec93-11e6-9fed-299fcb81caee.png)
![2](https://cloud.githubusercontent.com/assets/16865038/22641869/77e86496-ec93-11e6-8cce-3028db5937fe.jpg)
![3](https://cloud.githubusercontent.com/assets/16865038/22641902/94898634-ec93-11e6-9b01-9d165a3d382e.png)

**Comment by sorccu** [comment] 2017-02-06 09:45
Just check your browser's developer tools. It should tell you why it's
unable to connect.

**Comment by dududiao** [comment] 2017-02-07 02:47
Thanks  sorccu: I'm using a virtual machine, I don't find a solution to the document, WebSocket: the error is given 
![4](https://cloud.githubusercontent.com/assets/16865038/22675803/c57d5aec-ed22-11e6-9567-90b26674d3dc.jpg)

**Comment by sorccu** [comment] 2017-09-05 14:17
Closing as this is very old. 99% chance that the issue was caused by a misconfiguration.

**Closed by sorccu** 2017-09-05 14:17 UTC
