### ISSUE TITLE
when debug have a error ：address already in use

### ISSUE THREAD

**Issue by ruofeng086** [openstf/stf#636] opened 2017-06-28 07:02 UTC
when useing webstorm debug stf, have an error, can't start.

webstorm debug config:
![image](https://user-images.githubusercontent.com/14192308/27624139-0352d0dc-5c12-11e7-8bb4-8c1ff05dcc48.png)

error：
![image](https://user-images.githubusercontent.com/14192308/27624183-29bdec7a-5c12-11e7-9c92-28ce518f959e.png)
`Unable to open devtools socket: address already in use
Unable to open devtools socket: Unknown system error 0`

![image](https://user-images.githubusercontent.com/14192308/27624204-44b7c92e-5c12-11e7-8759-1b3198905457.png)

other mode no problem. no matter perform `stf local` or webstorm the run mode .

**Comment by sorccu** [comment] 2017-07-04 08:11
Duplicate of  #49 and #602.

**Closed by sorccu** 2017-07-04 08:11 UTC
