### ISSUE TITLE
DB is not initialized

### ISSUE THREAD

**Issue by perfectspr** [openstf/stf#535] opened 2017-02-09 08:12 UTC
**DB is not initialized when running stf local first time**

> FTL/reaper 12089 [reaper001] Unable to load initial state { ReqlOpFailedError: Database `stf` does not exist in:
> r.table("devices").getAll(true, {"index": "present"})
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     at ReqlOpFailedError.ReqlError [as constructor] (/stf/node_modules/rethinkdb/errors.js:23:13)
>     at ReqlOpFailedError.ReqlRuntimeError [as constructor] (/stf/node_modules/rethinkdb/errors.js:90:51)
>     at ReqlOpFailedError.ReqlAvailabilityError [as constructor] (/stf/node_modules/rethinkdb/errors.js:167:56)
>     at new ReqlOpFailedError (/stf/node_modules/rethinkdb/errors.js:178:52)
>     at mkErr (/stf/node_modules/rethinkdb/util.js:177:10)
>     at TcpConnection.Connection._processResponse (/stf/node_modules/rethinkdb/net.js:152:16)
>     at TcpConnection.Connection._data (/stf/node_modules/rethinkdb/net.js:122:12)
>     at Socket.<anonymous> (/stf/node_modules/rethinkdb/net.js:683:32)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:176:18)
>     at Socket.Readable.push (_stream_readable.js:134:10)
>     at TCP.onread (net.js:548:20)
> From previous event:
>     at GetAll.TermBase.run (/stf/node_modules/rethinkdb/ast.js:135:12)
>     at /stf/lib/db/index.js:129:14
>     at runCallback (timers.js:637:20)
>     at tryOnImmediate (timers.js:610:5)
>     at processImmediate [as _immediateCallback] (timers.js:582:5)
> From previous event:
>     at db.run (/stf/lib/db/index.js:128:23)
>     at dbapi.loadPresentDevices (/stf/lib/db/api.js:401:13)
>     at loadInitialState (/stf/lib/units/reaper/index.js:83:18)
>     at module.exports (/stf/lib/units/reaper/index.js:125:3)
>     at Object.module.exports.handler (/stf/lib/cli/reaper/index.js:42:39)
>     at Object.self.runCommand (/stf/node_modules/yargs/lib/command.js:170:22)
>     at parseArgs (/stf/node_modules/yargs/yargs.js:920:28)
>     at Object.get [as argv] (/stf/node_modules/yargs/yargs.js:860:16)
>     at Object.<anonymous> (/stf/lib/cli/index.js:40:3)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
>   name: 'ReqlOpFailedError',
>   msg: 'Database `stf` does not exist.',
>   frames: [],
>   message: 'Database `stf` does not exist in:\nr.table("devices").getAll(true, {"index": "present"})\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^' }
> FTL/util:lifecycle 12089 [reaper001] Shutting down due to fatal error
> FTL/cli:local 12083 [*] Child process had an error ExitError: Exit code "1"
>     at ChildProcess.<anonymous> (/stf/lib/util/procutil.js:49:23)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> INF/cli:local 12083 [*] Shutting down all child processes

last line of lib/cli/local/index.js
```javascript
  return procutil.fork(__filename, ['migrate'])
    .done(run)
```
should be 
```javascript
return procutil.fork(path.resolve(__dirname, '..'), ['migrate']).done(run)
```

**Comment by sorccu** [comment] 2017-02-09 08:14
Duplicate of #509 but that's a good call let me take a look. Let's continue in #509.

**Closed by sorccu** 2017-02-09 08:14 UTC
